"""Make seller_id nullable

Revision ID: 1c3f29e518bd
Revises: bd61371ba652
Create Date: 2025-10-30 18:23:08.439600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3f29e518bd'
down_revision = 'bd61371ba652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
