"""Make seller_id nullable in market

Revision ID: 211e0971ed58
Revises: 6b9119d46ba5
Create Date: 2025-10-31 02:56:31.977642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211e0971ed58'
down_revision = '6b9119d46ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('posts_user_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('posts_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
