"""Make seller_id nullable in market

Revision ID: 6b9119d46ba5
Revises: 1c3f29e518bd
Create Date: 2025-10-30 23:17:09.207876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9119d46ba5'
down_revision = '1c3f29e518bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
